# Generated by Django 4.1.1 on 2022-09-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('license_date', models.DateField()),
                ('license_expiry', models.IntegerField(choices=[(1, 'One Year'), (2, 'Two Years'), (3, 'Three Years'), (4, 'Four Years'), (5, 'Five Years')], default=1)),
            ],
            options={
                'ordering': ['license_date'],
            },
        ),
    ]
