# Generated by Django 4.1.1 on 2022-09-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gns3_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='router',
            name='ip',
        ),
        migrations.AddField(
            model_name='router',
            name='host',
            field=models.CharField(default=22, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='router',
            name='port',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
    ]
