# Generated by Django 4.1.1 on 2022-09-05 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('brand_sector', models.CharField(max_length=200)),
                ('brand_contact', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('DR', 'Dairy Product'), ('FR', 'Fresh Product'), ('CN', 'Canned Product'), ('MT', 'Meat, Chicken and Fish Product'), ('OT', 'Other Product')], default='OT', max_length=2)),
                ('price', models.FloatField()),
                ('unit', models.CharField(choices=[('KG', 'Kilogram'), ('UN', 'Unit'), ('LT', 'Litre')], default='UN', max_length=2)),
                ('barcode', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.brand')),
            ],
        ),
    ]
