# Generated by Django 4.1.1 on 2022-09-05 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supermarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supermarket_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('opening_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField()),
                ('number_in_stock', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('supermarket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supermarket')),
            ],
        ),
    ]
