# Generated by Django 4.1.1 on 2022-09-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supermarket_alter_product_barcode_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='supermarket_id',
            new_name='supermarket',
        ),
    ]
